# Generated by Django 5.1.7 on 2025-04-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter a quiz name", max_length=256),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_question", models.CharField(max_length=1024)),
                ("image_question", models.ImageField(upload_to="")),
                ("option1", models.CharField(max_length=64)),
                ("option2", models.CharField(max_length=64)),
                ("option3", models.CharField(max_length=64)),
                ("option4", models.CharField(max_length=64)),
                ("correct_option", models.IntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hello.myquiz",
                    ),
                ),
            ],
        ),
    ]
