# Generated by Django 5.1.7 on 2025-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myquiz",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
